### ISSUE TITLE
如何配置长连接呢？

### ISSUE THREAD

**Issue by wbdu** [membphis/nginx-tcp-lua-server#1]
如题

**Comment by membphis** [comment]
通过`ngx.req.socket()`获取客户端socket后，就可以通过`cosocket`接口完成所有后续功能。

api 查看：
http://wiki.nginx.org/HttpLuaModule#ngx.socket.tcp

nginx的连接，都是有客户端决定的。客户端不关闭，服务端是不会主动关闭的（除非自己设置了特定的超时关闭）

**Comment by daxiong380380** [comment]
@membphis 
@wbdu 
我现在的场景是利用stream模块来转发tcp流，所以我在content里面利用cosocket来与服务端建立长连接，这个连接会一直保持，我在测试过程中发现 nginx在转发结果给客户端后会主动关闭客户端的tcp连接，这是啥原因呢
