### ISSUE TITLE
客户端连接被nginx主动关闭

### ISSUE THREAD

**Issue by daxiong380380** [membphis/nginx-tcp-lua-server#2]
@membphis 
@wbdu 
我现在的场景是利用stream模块来转发tcp流，所以我在content里面利用cosocket来与服务端建立长连接，这个连接会一直保持，我在测试过程中发现 nginx在转发结果给客户端后会主动关闭客户端的tcp连接，这是啥原因呢

**Comment by membphis** [comment]
no chinese in here, thanks
